name: Saucy

on:
  workflow_dispatch:
  pull_request:
    branches: 'master'
  schedule:
    - cron: '0 1 * * *'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}
  IS_CRON_JOB: ${{ github.event_name == 'schedule' }}
  TITLE_NAME: ${{ toJSON(github.event) }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Print env vars
        run: |
          echo ${{ github.event_name }}
          date=$(TZ=":America/Chicago" date '+%m/%d/%Y')
          BRANCH_INFO=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          BUILD_DESCRIPTION=$([ "$IS_CRON_JOB" = true ] && echo "${date} Regression" || echo "${BRANCH_INFO}")
          echo TITLE_NAME - $TITLE_NAME
