name: Saucy 

on:
  pull_request:
    branches: 'master'
  workflow_dispatch:
    inputs:
      buildName:
        description: 'File name (optional)'
        default: 'CustomBuild'
        required: true

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_PR_BRANCH: ${{ github.head_ref }}
  COMMIT_MESSAGE: ${{ git log --format=%B -n 1 ${{ github.event.after }} }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print env vars
        run: |
          echo Build name: $BUILD_NAME
          echo PR Branch name: "${GITHUB_PR_BRANCH}"
          echo Commit message: "${COMMIT_MESSAGE}"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test