name: Saucy

on:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        description: Device
        options: 
        - handset
        - tablet
      testTag:
        description: Cucumber tag
        required: true
        default: ''
  push:
    branches: 'master'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}
  IS_MANUAL_TRIGGER: ${{ github.event_name == 'workflow_dispatch' }}
  TITLE_NAME: ${{ toJSON(github.event) }}
  TEST_TAG: ${{ github.event.inputs.testTag || "#Mock" }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cancel workflow
        run: |
          if [ true ]; then
            exit 0;
          fi
      - name: Print env vars
        run: |
          echo ${{ github.event_name }}
          date=$(TZ=":America/Chicago" date '+%m/%d/%Y')
          BRANCH_INFO=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          BUILD_DESCRIPTION=$([ "$IS_MANUAL_TRIGGER" = true ] && echo "${BRANCH_INFO}" || echo "${date} Regression")
          echo BUILD_DESCRIPTION - $BUILD_DESCRIPTION
