name: Saucy

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'File name (optional)'
        default: 'CustomBuild'
        required: true
  pull_request:
    branches: 'master'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Print env vars
        run: |
          BUILD_DESCRIPTION=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          echo $BUILD_DESCRIPTION
          echo $BUILD_DESC
