name: Saucy

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'File name (optional)'
        default: 'CustomBuild'
        required: true
  pull_request:
    branches: 'master'
  schedule:
    - cron: '0 1 * * *'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}
  IS_CRON_JOB: ${{ github.event_name == 'schedule'  }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Print env vars
        run: |
          echo IS_CRON_JOB - $IS_CRON_JOB
          date=$(date '+%d/%m/%Y')
          BUILD_DESCRIPTION=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          B_DESC=$([ "$IS_CRON_JOB" = false ] && echo "${date} Regression" || echo "${BUILD_DESCRIPTION}")
          echo B_DESC - $B_DESC
