name: Saucy 

on:
  pull_request:
    branches: 'master'
  workflow_dispatch:
    inputs:
      buildName:
        description: 'File name (optional)'
        default: 'CustomBuild'
        required: true

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  # COMMIT_MESSAGE: ${{ git log -1 --pretty=%B }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print env vars
        run: |
          echo Build name: $BUILD_NAME
          echo Commit message: "$(git log -1 --pretty=%B)"
          echo ${{ toJSON(github) }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test