name: Saucy

on:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        description: Device
        options: 
        - handset
        - tablet
      testTag:
        description: Cucumber tag
        default: ''
      branch:
        description: Branch name
        default: 'release/322.0'
  push:
    branches: 'master'
  schedule:
    - cron: '5 2 * * *'
    - cron: '25 2 * * *'
    - cron: '30 3 * * *'
    - cron: '30 5 * * *'
    - cron: '0 12 * * *'
  repository_dispatch:
    types: [run-test]

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}
  IS_MANUAL_TRIGGER: ${{ github.event_name == 'workflow_dispatch' }}
  GITHUB_EVENT: ${{ toJSON(github) }}
  TEST_TAG: ${{ github.event.inputs.testTag || '@Mock' }} 
  BRANCH_NAME: ${{ github.event.inputs.branch || github.event.repository.default_branch }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cancel workflow
        run: |
          echo EVENT $GITHUB_EVENT
          echo BRANCH $BRANCH_NAME
          echo TEST_TAG ${TEST_TAG}
          if [ true ]; then
            exit 0;
          fi
      - name: Print env vars
        run: |
          echo ${{ github.event_name }}
          date=$(TZ=":America/Chicago" date '+%m/%d/%Y')
          BRANCH_INFO=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          BUILD_DESCRIPTION=$([ "$IS_MANUAL_TRIGGER" = true ] && echo "${BRANCH_INFO}" || echo "${date} Regression")
          echo BUILD_DESCRIPTION - $BUILD_DESCRIPTION
