name: Saucy

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'File name (optional)'
        default: 'CustomBuild'
        required: true
  pull_request:
    branches: 'master'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print env vars
        run: |
          BUILD_DESCRIPTION=$(echo $(git log -1 --pretty=%B))
          echo ${{ toJSON(github.event) }}
          echo BUILD_DESCRIPTION - $BUILD_DESCRIPTION
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
