name: Saucy

on:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        description: Device
        options: 
        - handset
        - tablet
      testTag:
        description: Cucumber tag
        default: ''
      branch:
        description: Branch name
        default: 'release/322.0'
      build-apk:
        type: boolean
        description: Build and upload .apk (Android emulators/real devices)
  push:
    branches: 'master'

env:
  BUILD_NAME: ${{ github.event.inputs.buildName || 'DefaultFilename' }}
  GITHUB_BRANCH: ${{ github.event.ref }}
  # BUILD_DESCRIPTION: ${{ github.event.ref $(git log -1 --pretty=%B)) }}
  BUILD_DESC: ${{ toJSON(github) }}
  IS_MANUAL_TRIGGER: ${{ github.event_name == 'workflow_dispatch' }}
  GITHUB_EVENT: ${{ toJSON(github) }}
  TEST_TAG: ${{ github.event.inputs.testTag || '@Mock' }} 
  BRANCH_NAME: ${{ github.event.inputs.branch || github.event.repository.default_branch }}
  ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

jobs:
  print-env-var:
    name: Print env var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cancel workflow
        run: |
          npm install -g typescript
          npm install -g ts-node
          
          echo TS-NODE
          which ts-node

          ts-node script.ts

          # echo CHECKBOX INPUT - ${{ github.event.inputs.build-apk }}

          # echo EVENT $GITHUB_EVENT
          # echo BRANCH $BRANCH_NAME
          # echo TEST_TAG ${TEST_TAG}
          # if [ true ]; then
          #   exit 0;
          # fi
      - name: Run if build-apk checked
        if: ${{ github.event.inputs.build-apk == 'true' }}
        run: echo Job ran
      - name: Print env vars
        run: |
          echo ${{ github.event_name }}
          date=$(TZ=":America/Chicago" date '+%m/%d/%Y')
          BRANCH_INFO=$(echo ${GITHUB_BRANCH:11} - $(git log -1 --pretty=%B))
          BUILD_DESCRIPTION=$([ "$IS_MANUAL_TRIGGER" = true ] && echo "${BRANCH_INFO}" || echo "${date} Regression")
          echo BUILD_DESCRIPTION - $BUILD_DESCRIPTION
      # - name: Dispatch tests
      #   run: |
      #     for i in {1..5}
      #     do
      #       sleep 5
      #       echo SEND DISPATCH
      #       curl -X POST -H "Authorization: Bearer ${ACTIONS_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/BlackSwan2019/actionsTesting/dispatches -d '{"event_type":"run-test","client_payload":{"unit":false,"integration":true}}'
      #     done
