name: Hello World

on:
  push:
    branches: master

jobs:
  print-env-var:
    name: Hello World
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello World
        run: echo "Hello world!"
